{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "c3d9faa1",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "9394e516",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>PRT_ID</th>\n",
       "      <th>AREA</th>\n",
       "      <th>INT_SQFT</th>\n",
       "      <th>DATE_SALE</th>\n",
       "      <th>DIST_MAINROAD</th>\n",
       "      <th>N_BEDROOM</th>\n",
       "      <th>N_BATHROOM</th>\n",
       "      <th>N_ROOM</th>\n",
       "      <th>SALE_COND</th>\n",
       "      <th>PARK_FACIL</th>\n",
       "      <th>...</th>\n",
       "      <th>UTILITY_AVAIL</th>\n",
       "      <th>STREET</th>\n",
       "      <th>MZZONE</th>\n",
       "      <th>QS_ROOMS</th>\n",
       "      <th>QS_BATHROOM</th>\n",
       "      <th>QS_BEDROOM</th>\n",
       "      <th>QS_OVERALL</th>\n",
       "      <th>REG_FEE</th>\n",
       "      <th>COMMIS</th>\n",
       "      <th>SALES_PRICE</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>P03210</td>\n",
       "      <td>Karapakkam</td>\n",
       "      <td>1004</td>\n",
       "      <td>04-05-2011</td>\n",
       "      <td>131</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>3</td>\n",
       "      <td>AbNormal</td>\n",
       "      <td>Yes</td>\n",
       "      <td>...</td>\n",
       "      <td>AllPub</td>\n",
       "      <td>Paved</td>\n",
       "      <td>A</td>\n",
       "      <td>4.0</td>\n",
       "      <td>3.9</td>\n",
       "      <td>4.9</td>\n",
       "      <td>4.330</td>\n",
       "      <td>380000</td>\n",
       "      <td>144400</td>\n",
       "      <td>7600000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>P09411</td>\n",
       "      <td>Anna Nagar</td>\n",
       "      <td>1986</td>\n",
       "      <td>19-12-2006</td>\n",
       "      <td>26</td>\n",
       "      <td>2.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>5</td>\n",
       "      <td>AbNormal</td>\n",
       "      <td>No</td>\n",
       "      <td>...</td>\n",
       "      <td>AllPub</td>\n",
       "      <td>Gravel</td>\n",
       "      <td>RH</td>\n",
       "      <td>4.9</td>\n",
       "      <td>4.2</td>\n",
       "      <td>2.5</td>\n",
       "      <td>3.765</td>\n",
       "      <td>760122</td>\n",
       "      <td>304049</td>\n",
       "      <td>21717770</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>P01812</td>\n",
       "      <td>Adyar</td>\n",
       "      <td>909</td>\n",
       "      <td>04-02-2012</td>\n",
       "      <td>70</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>3</td>\n",
       "      <td>AbNormal</td>\n",
       "      <td>Yes</td>\n",
       "      <td>...</td>\n",
       "      <td>ELO</td>\n",
       "      <td>Gravel</td>\n",
       "      <td>RL</td>\n",
       "      <td>4.1</td>\n",
       "      <td>3.8</td>\n",
       "      <td>2.2</td>\n",
       "      <td>3.090</td>\n",
       "      <td>421094</td>\n",
       "      <td>92114</td>\n",
       "      <td>13159200</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>P05346</td>\n",
       "      <td>Velachery</td>\n",
       "      <td>1855</td>\n",
       "      <td>13-03-2010</td>\n",
       "      <td>14</td>\n",
       "      <td>3.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>5</td>\n",
       "      <td>Family</td>\n",
       "      <td>No</td>\n",
       "      <td>...</td>\n",
       "      <td>NoSewr</td>\n",
       "      <td>Paved</td>\n",
       "      <td>I</td>\n",
       "      <td>4.7</td>\n",
       "      <td>3.9</td>\n",
       "      <td>3.6</td>\n",
       "      <td>4.010</td>\n",
       "      <td>356321</td>\n",
       "      <td>77042</td>\n",
       "      <td>9630290</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>P06210</td>\n",
       "      <td>Karapakkam</td>\n",
       "      <td>1226</td>\n",
       "      <td>05-10-2009</td>\n",
       "      <td>84</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>3</td>\n",
       "      <td>AbNormal</td>\n",
       "      <td>Yes</td>\n",
       "      <td>...</td>\n",
       "      <td>AllPub</td>\n",
       "      <td>Gravel</td>\n",
       "      <td>C</td>\n",
       "      <td>3.0</td>\n",
       "      <td>2.5</td>\n",
       "      <td>4.1</td>\n",
       "      <td>3.290</td>\n",
       "      <td>237000</td>\n",
       "      <td>74063</td>\n",
       "      <td>7406250</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 22 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "   PRT_ID        AREA  INT_SQFT   DATE_SALE  DIST_MAINROAD  N_BEDROOM  \\\n",
       "0  P03210  Karapakkam      1004  04-05-2011            131        1.0   \n",
       "1  P09411  Anna Nagar      1986  19-12-2006             26        2.0   \n",
       "2  P01812       Adyar       909  04-02-2012             70        1.0   \n",
       "3  P05346   Velachery      1855  13-03-2010             14        3.0   \n",
       "4  P06210  Karapakkam      1226  05-10-2009             84        1.0   \n",
       "\n",
       "   N_BATHROOM  N_ROOM SALE_COND PARK_FACIL  ... UTILITY_AVAIL  STREET MZZONE  \\\n",
       "0         1.0       3  AbNormal        Yes  ...        AllPub   Paved      A   \n",
       "1         1.0       5  AbNormal         No  ...        AllPub  Gravel     RH   \n",
       "2         1.0       3  AbNormal        Yes  ...           ELO  Gravel     RL   \n",
       "3         2.0       5    Family         No  ...       NoSewr    Paved      I   \n",
       "4         1.0       3  AbNormal        Yes  ...        AllPub  Gravel      C   \n",
       "\n",
       "  QS_ROOMS QS_BATHROOM  QS_BEDROOM  QS_OVERALL  REG_FEE  COMMIS  SALES_PRICE  \n",
       "0      4.0         3.9         4.9       4.330   380000  144400      7600000  \n",
       "1      4.9         4.2         2.5       3.765   760122  304049     21717770  \n",
       "2      4.1         3.8         2.2       3.090   421094   92114     13159200  \n",
       "3      4.7         3.9         3.6       4.010   356321   77042      9630290  \n",
       "4      3.0         2.5         4.1       3.290   237000   74063      7406250  \n",
       "\n",
       "[5 rows x 22 columns]"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df1 = pd.read_csv('train.csv')\n",
    "df1.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "00b493cf",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "62bc27c5",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>AREA</th>\n",
       "      <th>INT_SQFT</th>\n",
       "      <th>DIST_MAINROAD</th>\n",
       "      <th>N_BEDROOM</th>\n",
       "      <th>N_BATHROOM</th>\n",
       "      <th>PARK_FACIL</th>\n",
       "      <th>DATE_SALE</th>\n",
       "      <th>DATE_BUILD</th>\n",
       "      <th>STREET</th>\n",
       "      <th>SALES_PRICE</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Karapakkam</td>\n",
       "      <td>1004</td>\n",
       "      <td>131</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Yes</td>\n",
       "      <td>04-05-2011</td>\n",
       "      <td>15-05-1967</td>\n",
       "      <td>Paved</td>\n",
       "      <td>7600000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Anna Nagar</td>\n",
       "      <td>1986</td>\n",
       "      <td>26</td>\n",
       "      <td>2.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>No</td>\n",
       "      <td>19-12-2006</td>\n",
       "      <td>22-12-1995</td>\n",
       "      <td>Gravel</td>\n",
       "      <td>21717770</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Adyar</td>\n",
       "      <td>909</td>\n",
       "      <td>70</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Yes</td>\n",
       "      <td>04-02-2012</td>\n",
       "      <td>09-02-1992</td>\n",
       "      <td>Gravel</td>\n",
       "      <td>13159200</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Velachery</td>\n",
       "      <td>1855</td>\n",
       "      <td>14</td>\n",
       "      <td>3.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>No</td>\n",
       "      <td>13-03-2010</td>\n",
       "      <td>18-03-1988</td>\n",
       "      <td>Paved</td>\n",
       "      <td>9630290</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Karapakkam</td>\n",
       "      <td>1226</td>\n",
       "      <td>84</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Yes</td>\n",
       "      <td>05-10-2009</td>\n",
       "      <td>13-10-1979</td>\n",
       "      <td>Gravel</td>\n",
       "      <td>7406250</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "         AREA  INT_SQFT  DIST_MAINROAD  N_BEDROOM  N_BATHROOM PARK_FACIL  \\\n",
       "0  Karapakkam      1004            131        1.0         1.0        Yes   \n",
       "1  Anna Nagar      1986             26        2.0         1.0         No   \n",
       "2       Adyar       909             70        1.0         1.0        Yes   \n",
       "3   Velachery      1855             14        3.0         2.0         No   \n",
       "4  Karapakkam      1226             84        1.0         1.0        Yes   \n",
       "\n",
       "    DATE_SALE  DATE_BUILD  STREET  SALES_PRICE  \n",
       "0  04-05-2011  15-05-1967   Paved      7600000  \n",
       "1  19-12-2006  22-12-1995  Gravel     21717770  \n",
       "2  04-02-2012  09-02-1992  Gravel     13159200  \n",
       "3  13-03-2010  18-03-1988   Paved      9630290  \n",
       "4  05-10-2009  13-10-1979  Gravel      7406250  "
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df2 = df1[['AREA', 'INT_SQFT', 'DIST_MAINROAD', 'N_BEDROOM', 'N_BATHROOM', 'PARK_FACIL','DATE_SALE', 'DATE_BUILD', 'STREET', 'SALES_PRICE']]\n",
    "df2\n",
    "df2.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "670c7abf",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>AREA</th>\n",
       "      <th>SQFT</th>\n",
       "      <th>DIST_MAINROAD</th>\n",
       "      <th>NO_BED</th>\n",
       "      <th>NO_BATH</th>\n",
       "      <th>PARK</th>\n",
       "      <th>DATE_SALE</th>\n",
       "      <th>DATE_BUILD</th>\n",
       "      <th>STREET</th>\n",
       "      <th>PRICE</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Karapakkam</td>\n",
       "      <td>1004</td>\n",
       "      <td>131</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Yes</td>\n",
       "      <td>04-05-2011</td>\n",
       "      <td>15-05-1967</td>\n",
       "      <td>Paved</td>\n",
       "      <td>7600000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Anna Nagar</td>\n",
       "      <td>1986</td>\n",
       "      <td>26</td>\n",
       "      <td>2.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>No</td>\n",
       "      <td>19-12-2006</td>\n",
       "      <td>22-12-1995</td>\n",
       "      <td>Gravel</td>\n",
       "      <td>21717770</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Adyar</td>\n",
       "      <td>909</td>\n",
       "      <td>70</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Yes</td>\n",
       "      <td>04-02-2012</td>\n",
       "      <td>09-02-1992</td>\n",
       "      <td>Gravel</td>\n",
       "      <td>13159200</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Velachery</td>\n",
       "      <td>1855</td>\n",
       "      <td>14</td>\n",
       "      <td>3.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>No</td>\n",
       "      <td>13-03-2010</td>\n",
       "      <td>18-03-1988</td>\n",
       "      <td>Paved</td>\n",
       "      <td>9630290</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Karapakkam</td>\n",
       "      <td>1226</td>\n",
       "      <td>84</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Yes</td>\n",
       "      <td>05-10-2009</td>\n",
       "      <td>13-10-1979</td>\n",
       "      <td>Gravel</td>\n",
       "      <td>7406250</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "         AREA  SQFT  DIST_MAINROAD  NO_BED  NO_BATH PARK   DATE_SALE  \\\n",
       "0  Karapakkam  1004            131     1.0      1.0  Yes  04-05-2011   \n",
       "1  Anna Nagar  1986             26     2.0      1.0   No  19-12-2006   \n",
       "2       Adyar   909             70     1.0      1.0  Yes  04-02-2012   \n",
       "3   Velachery  1855             14     3.0      2.0   No  13-03-2010   \n",
       "4  Karapakkam  1226             84     1.0      1.0  Yes  05-10-2009   \n",
       "\n",
       "   DATE_BUILD  STREET     PRICE  \n",
       "0  15-05-1967   Paved   7600000  \n",
       "1  22-12-1995  Gravel  21717770  \n",
       "2  09-02-1992  Gravel  13159200  \n",
       "3  18-03-1988   Paved   9630290  \n",
       "4  13-10-1979  Gravel   7406250  "
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df3 = df2.rename(columns={'INT_SQFT':'SQFT','N_BEDROOM':'NO_BED','N_BATHROOM':'NO_BATH','PARK_FACIL':'PARK','SALES_PRICE':'PRICE'})\n",
    "df3.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "b810eb07",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>AREA</th>\n",
       "      <th>SQFT</th>\n",
       "      <th>DIST_MAINROAD</th>\n",
       "      <th>NO_BED</th>\n",
       "      <th>NO_BATH</th>\n",
       "      <th>PARK</th>\n",
       "      <th>DATE_SALE</th>\n",
       "      <th>DATE_BUILD</th>\n",
       "      <th>STREET</th>\n",
       "      <th>PRICE</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Karapakkam</td>\n",
       "      <td>1004</td>\n",
       "      <td>131</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Yes</td>\n",
       "      <td>04-05-2011</td>\n",
       "      <td>15-05-1967</td>\n",
       "      <td>Paved</td>\n",
       "      <td>7600000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Anna Nagar</td>\n",
       "      <td>1986</td>\n",
       "      <td>26</td>\n",
       "      <td>2.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>No</td>\n",
       "      <td>19-12-2006</td>\n",
       "      <td>22-12-1995</td>\n",
       "      <td>Gravel</td>\n",
       "      <td>21717770</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Adyar</td>\n",
       "      <td>909</td>\n",
       "      <td>70</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Yes</td>\n",
       "      <td>04-02-2012</td>\n",
       "      <td>09-02-1992</td>\n",
       "      <td>Gravel</td>\n",
       "      <td>13159200</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Velachery</td>\n",
       "      <td>1855</td>\n",
       "      <td>14</td>\n",
       "      <td>3.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>No</td>\n",
       "      <td>13-03-2010</td>\n",
       "      <td>18-03-1988</td>\n",
       "      <td>Paved</td>\n",
       "      <td>9630290</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Karapakkam</td>\n",
       "      <td>1226</td>\n",
       "      <td>84</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Yes</td>\n",
       "      <td>05-10-2009</td>\n",
       "      <td>13-10-1979</td>\n",
       "      <td>Gravel</td>\n",
       "      <td>7406250</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "         AREA  SQFT  DIST_MAINROAD  NO_BED  NO_BATH PARK   DATE_SALE  \\\n",
       "0  Karapakkam  1004            131     1.0      1.0  Yes  04-05-2011   \n",
       "1  Anna Nagar  1986             26     2.0      1.0   No  19-12-2006   \n",
       "2       Adyar   909             70     1.0      1.0  Yes  04-02-2012   \n",
       "3   Velachery  1855             14     3.0      2.0   No  13-03-2010   \n",
       "4  Karapakkam  1226             84     1.0      1.0  Yes  05-10-2009   \n",
       "\n",
       "   DATE_BUILD  STREET     PRICE  \n",
       "0  15-05-1967   Paved   7600000  \n",
       "1  22-12-1995  Gravel  21717770  \n",
       "2  09-02-1992  Gravel  13159200  \n",
       "3  18-03-1988   Paved   9630290  \n",
       "4  13-10-1979  Gravel   7406250  "
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df4 = df3.dropna()\n",
    "df4.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "47593fc3",
   "metadata": {},
   "outputs": [],
   "source": [
    "from datetime import datetime, date\n",
    "def age(date_sale, date_build):\n",
    "    datesold = datetime.strptime(date_sale, \"%d-%m-%Y\").date()\n",
    "    datebuilt = datetime.strptime(date_build, \"%d-%m-%Y\").date()\n",
    "    return datesold.year - datebuilt.year - ((datesold.month,\n",
    "                                          datesold.day) < (datebuilt.month,\n",
    "                                                        datebuilt.day))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "13b4ca80",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>AREA</th>\n",
       "      <th>SQFT</th>\n",
       "      <th>DIST_MAINROAD</th>\n",
       "      <th>NO_BED</th>\n",
       "      <th>NO_BATH</th>\n",
       "      <th>PARK</th>\n",
       "      <th>DATE_SALE</th>\n",
       "      <th>DATE_BUILD</th>\n",
       "      <th>STREET</th>\n",
       "      <th>PRICE</th>\n",
       "      <th>AGE</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Karapakkam</td>\n",
       "      <td>1004</td>\n",
       "      <td>131</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Yes</td>\n",
       "      <td>04-05-2011</td>\n",
       "      <td>15-05-1967</td>\n",
       "      <td>Paved</td>\n",
       "      <td>7600000</td>\n",
       "      <td>43</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Anna Nagar</td>\n",
       "      <td>1986</td>\n",
       "      <td>26</td>\n",
       "      <td>2.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>No</td>\n",
       "      <td>19-12-2006</td>\n",
       "      <td>22-12-1995</td>\n",
       "      <td>Gravel</td>\n",
       "      <td>21717770</td>\n",
       "      <td>10</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Adyar</td>\n",
       "      <td>909</td>\n",
       "      <td>70</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Yes</td>\n",
       "      <td>04-02-2012</td>\n",
       "      <td>09-02-1992</td>\n",
       "      <td>Gravel</td>\n",
       "      <td>13159200</td>\n",
       "      <td>19</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Velachery</td>\n",
       "      <td>1855</td>\n",
       "      <td>14</td>\n",
       "      <td>3.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>No</td>\n",
       "      <td>13-03-2010</td>\n",
       "      <td>18-03-1988</td>\n",
       "      <td>Paved</td>\n",
       "      <td>9630290</td>\n",
       "      <td>21</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Karapakkam</td>\n",
       "      <td>1226</td>\n",
       "      <td>84</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Yes</td>\n",
       "      <td>05-10-2009</td>\n",
       "      <td>13-10-1979</td>\n",
       "      <td>Gravel</td>\n",
       "      <td>7406250</td>\n",
       "      <td>29</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "         AREA  SQFT  DIST_MAINROAD  NO_BED  NO_BATH PARK   DATE_SALE  \\\n",
       "0  Karapakkam  1004            131     1.0      1.0  Yes  04-05-2011   \n",
       "1  Anna Nagar  1986             26     2.0      1.0   No  19-12-2006   \n",
       "2       Adyar   909             70     1.0      1.0  Yes  04-02-2012   \n",
       "3   Velachery  1855             14     3.0      2.0   No  13-03-2010   \n",
       "4  Karapakkam  1226             84     1.0      1.0  Yes  05-10-2009   \n",
       "\n",
       "   DATE_BUILD  STREET     PRICE  AGE  \n",
       "0  15-05-1967   Paved   7600000   43  \n",
       "1  22-12-1995  Gravel  21717770   10  \n",
       "2  09-02-1992  Gravel  13159200   19  \n",
       "3  18-03-1988   Paved   9630290   21  \n",
       "4  13-10-1979  Gravel   7406250   29  "
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df5 = df4.copy()\n",
    "df5['AGE'] = df5.apply(lambda x: age(x.DATE_SALE, x.DATE_BUILD), axis=1)\n",
    "df5.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "51951cb1",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>AREA</th>\n",
       "      <th>SQFT</th>\n",
       "      <th>DIST_MAINROAD</th>\n",
       "      <th>NO_BED</th>\n",
       "      <th>NO_BATH</th>\n",
       "      <th>PARK</th>\n",
       "      <th>STREET</th>\n",
       "      <th>PRICE</th>\n",
       "      <th>AGE</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Karapakkam</td>\n",
       "      <td>1004</td>\n",
       "      <td>131</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Paved</td>\n",
       "      <td>7600000</td>\n",
       "      <td>43</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Anna Nagar</td>\n",
       "      <td>1986</td>\n",
       "      <td>26</td>\n",
       "      <td>2.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>No</td>\n",
       "      <td>Gravel</td>\n",
       "      <td>21717770</td>\n",
       "      <td>10</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Adyar</td>\n",
       "      <td>909</td>\n",
       "      <td>70</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Gravel</td>\n",
       "      <td>13159200</td>\n",
       "      <td>19</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Velachery</td>\n",
       "      <td>1855</td>\n",
       "      <td>14</td>\n",
       "      <td>3.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>No</td>\n",
       "      <td>Paved</td>\n",
       "      <td>9630290</td>\n",
       "      <td>21</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Karapakkam</td>\n",
       "      <td>1226</td>\n",
       "      <td>84</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Gravel</td>\n",
       "      <td>7406250</td>\n",
       "      <td>29</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "         AREA  SQFT  DIST_MAINROAD  NO_BED  NO_BATH PARK  STREET     PRICE  \\\n",
       "0  Karapakkam  1004            131     1.0      1.0  Yes   Paved   7600000   \n",
       "1  Anna Nagar  1986             26     2.0      1.0   No  Gravel  21717770   \n",
       "2       Adyar   909             70     1.0      1.0  Yes  Gravel  13159200   \n",
       "3   Velachery  1855             14     3.0      2.0   No   Paved   9630290   \n",
       "4  Karapakkam  1226             84     1.0      1.0  Yes  Gravel   7406250   \n",
       "\n",
       "   AGE  \n",
       "0   43  \n",
       "1   10  \n",
       "2   19  \n",
       "3   21  \n",
       "4   29  "
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df6 = df5.drop(['DATE_SALE', 'DATE_BUILD'], axis=1)\n",
    "df6.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "37b52359",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array(['Karapakkam', 'Anna Nagar', 'Adyar', 'Velachery', 'Chrompet',\n",
       "       'KK Nagar', 'TNagar', 'T Nagar', 'Chrompt', 'Chrmpet', 'Karapakam',\n",
       "       'Ana Nagar', 'Chormpet', 'Adyr', 'Velchery', 'Ann Nagar',\n",
       "       'KKNagar'], dtype=object)"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df6['AREA'].unique()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "68686815",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>AREA</th>\n",
       "      <th>SQFT</th>\n",
       "      <th>DIST_MAINROAD</th>\n",
       "      <th>NO_BED</th>\n",
       "      <th>NO_BATH</th>\n",
       "      <th>PARK</th>\n",
       "      <th>STREET</th>\n",
       "      <th>PRICE</th>\n",
       "      <th>AGE</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Karapakkam</td>\n",
       "      <td>1004</td>\n",
       "      <td>131</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Paved</td>\n",
       "      <td>7600000</td>\n",
       "      <td>43</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Anna Nagar</td>\n",
       "      <td>1986</td>\n",
       "      <td>26</td>\n",
       "      <td>2.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>No</td>\n",
       "      <td>Gravel</td>\n",
       "      <td>21717770</td>\n",
       "      <td>10</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Adyar</td>\n",
       "      <td>909</td>\n",
       "      <td>70</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Gravel</td>\n",
       "      <td>13159200</td>\n",
       "      <td>19</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Velachery</td>\n",
       "      <td>1855</td>\n",
       "      <td>14</td>\n",
       "      <td>3.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>No</td>\n",
       "      <td>Paved</td>\n",
       "      <td>9630290</td>\n",
       "      <td>21</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Karapakkam</td>\n",
       "      <td>1226</td>\n",
       "      <td>84</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Gravel</td>\n",
       "      <td>7406250</td>\n",
       "      <td>29</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "         AREA  SQFT  DIST_MAINROAD  NO_BED  NO_BATH PARK  STREET     PRICE  \\\n",
       "0  Karapakkam  1004            131     1.0      1.0  Yes   Paved   7600000   \n",
       "1  Anna Nagar  1986             26     2.0      1.0   No  Gravel  21717770   \n",
       "2       Adyar   909             70     1.0      1.0  Yes  Gravel  13159200   \n",
       "3   Velachery  1855             14     3.0      2.0   No   Paved   9630290   \n",
       "4  Karapakkam  1226             84     1.0      1.0  Yes  Gravel   7406250   \n",
       "\n",
       "   AGE  \n",
       "0   43  \n",
       "1   10  \n",
       "2   19  \n",
       "3   21  \n",
       "4   29  "
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df7 = df6.copy()\n",
    "df7.loc[df7['AREA'] == 'TNagar', 'AREA'] = 'T Nagar'\n",
    "df7.loc[df7['AREA'] == 'Chrompt', 'AREA'] = 'Chrompet'\n",
    "df7.loc[df7['AREA'] == 'Chrmpet', 'AREA'] = 'Chrompet'\n",
    "df7.loc[df7['AREA'] == 'Chormpet', 'AREA'] = 'Chrompet'\n",
    "df7.loc[df7['AREA'] == 'Ana Nagar', 'AREA'] = 'Anna Nagar'\n",
    "df7.loc[df7['AREA'] == 'Adyr', 'AREA'] = 'Adyar'\n",
    "df7.loc[df7['AREA'] == 'Velchery', 'AREA'] = 'Velachery'\n",
    "df7.loc[df7['AREA'] == 'Ann Nagar', 'AREA'] = 'Anna Nagar'\n",
    "df7.loc[df7['AREA'] == 'KKNagar', 'AREA'] = 'KK Nagar'\n",
    "df7.loc[df7['AREA'] == 'Karapakam', 'AREA'] = 'Karapakkam'\n",
    "df7.loc[df7['STREET'] == 'Pavd', 'STREET'] = 'Paved'\n",
    "df7.loc[df7['STREET'] == 'NoAccess', 'STREET'] = 'No Access'\n",
    "df7.loc[df7['PARK'] == 'Noo', 'PARK'] = 'No'\n",
    "df7.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "5540fff4",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>AREA</th>\n",
       "      <th>SQFT</th>\n",
       "      <th>DIST_MAINROAD</th>\n",
       "      <th>NO_BED</th>\n",
       "      <th>NO_BATH</th>\n",
       "      <th>PARK</th>\n",
       "      <th>STREET</th>\n",
       "      <th>PRICE</th>\n",
       "      <th>AGE</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Karapakkam</td>\n",
       "      <td>1004</td>\n",
       "      <td>131</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1</td>\n",
       "      <td>Paved</td>\n",
       "      <td>7600000</td>\n",
       "      <td>43</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Anna Nagar</td>\n",
       "      <td>1986</td>\n",
       "      <td>26</td>\n",
       "      <td>2.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0</td>\n",
       "      <td>Gravel</td>\n",
       "      <td>21717770</td>\n",
       "      <td>10</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Adyar</td>\n",
       "      <td>909</td>\n",
       "      <td>70</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1</td>\n",
       "      <td>Gravel</td>\n",
       "      <td>13159200</td>\n",
       "      <td>19</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Velachery</td>\n",
       "      <td>1855</td>\n",
       "      <td>14</td>\n",
       "      <td>3.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>0</td>\n",
       "      <td>Paved</td>\n",
       "      <td>9630290</td>\n",
       "      <td>21</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Karapakkam</td>\n",
       "      <td>1226</td>\n",
       "      <td>84</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1</td>\n",
       "      <td>Gravel</td>\n",
       "      <td>7406250</td>\n",
       "      <td>29</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "         AREA  SQFT  DIST_MAINROAD  NO_BED  NO_BATH  PARK  STREET     PRICE  \\\n",
       "0  Karapakkam  1004            131     1.0      1.0     1   Paved   7600000   \n",
       "1  Anna Nagar  1986             26     2.0      1.0     0  Gravel  21717770   \n",
       "2       Adyar   909             70     1.0      1.0     1  Gravel  13159200   \n",
       "3   Velachery  1855             14     3.0      2.0     0   Paved   9630290   \n",
       "4  Karapakkam  1226             84     1.0      1.0     1  Gravel   7406250   \n",
       "\n",
       "   AGE  \n",
       "0   43  \n",
       "1   10  \n",
       "2   19  \n",
       "3   21  \n",
       "4   29  "
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df8 = df7.replace({'PARK': {'Yes': 1, \n",
    "                                'No': 0}})\n",
    "df8.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "78f95eb0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "AREA\n",
      "Adyar          774\n",
      "Anna Nagar     785\n",
      "Chrompet      1699\n",
      "KK Nagar       997\n",
      "Karapakkam    1366\n",
      "T Nagar        501\n",
      "Velachery      981\n",
      "Name: AREA, dtype: int64\n"
     ]
    }
   ],
   "source": [
    "print(df8.groupby('AREA')['AREA'].agg('count'))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "fde94eac",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Text(0.5, 1.0, 'Sqft Rate Graph')"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAYsAAAEWCAYAAACXGLsWAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAAec0lEQVR4nO3de5gdVZnv8e/PhIsimMS0mZBEOvAEnIBDhObiCIrCSACPqIeBZFRA0aiAijA6wcsRmOEcLqJOQMEAEThyiyAauQxGR2VEuXRiCAkQ6YRwkhhIA5IgciLBd/6otaXS7O7avbNvnf37PE89XbXq9vbKzn671lpVpYjAzMxsIK9qdgBmZtb6nCzMzKyQk4WZmRVysjAzs0JOFmZmVsjJwszMCjlZWNuRNEbSXZKek3RRs+NpRZIOkbS62XFY63CysCFJ0kGSfi1pvaRnJN0tab8Kd58BPAXsFBFnSPqFpI8NcK5OSSHpj2laKWnmIGK9StK/Vbp9P8foknSrpD9IelbSQ5LOlTRyS45rViknCxtyJO0E3ApcDIwCxgFnAxsrPMQuwEMx+DtSR0TEa4FjgK9I+odB7l8VSX8P/AK4G3hTRIwApgKbgL372Wd4I2KzNhIRnjwNqQnoAp4dYP0w4GtkVw8rgFOAAIYDVwEvAn8G/kj2BfwS8P/T8iVljtdZ2j9Xdh/w+dzy94EngPXAXcCeqXxGn/P9OJXvDNwM9AKPAZ8Z4Pf5FXBxQZ2cmH6XbwBPA/8G7Ab8Z1p+CriWLOGV9lkJnAk8BPwB+C6wfVp3CLAaOANYB6wFPtLsf3tPzZt8ZWFD0e+AlyRdLemIMk0xHwfeA7yFLLEcU1oRESeSfWleEBGvjYi3Af8FnJqWTy06uaQDgb2AnlzxHcAk4A3AwnQOImJ2n/P9D0mvAn4MPEB2VXQocJqkw8ucawfgrWSJpcgBZMlxDHAuIOD/kCWmvwUmAGf12eeDwOFkiWV34Mu5dX8DvC7FeBLwLTd7tS8nCxtyImIDcBDZX/uXA72S5kkakzY5FvhmRKyKiGfIvjBr4SlJLwC/Ab4N/DAX05yIeC4iNpJ9Ie8t6XX9HGc/oCMizomIP0fEivR7TCuz7Uiy/6dPlAokXZD6LZ6XlP9y/31EXBwRmyLihYjoiYj5EbExInqBrwPv6HP8S3L1dC4wPbfuReCciHgxIm4nuzLaY+Aqsq2Vk4UNSRHxcEScGBHjyf7K3xn4Zlq9M7Aqt/njNTrtaOC1ZE0zhwDbAEgaJuk8ScslbSBr3iltX84uwM7pC/9ZSc8CXyS7IujrD8BfgLGlgoj4QmT9FreQNa2V5H/n0qivGyStSXF9r0xMfetp59zy0xGxKbf8J7Lf39qQk4UNeRHxCFlfxF6paC1Zk0vJG4sOMYhzvRQRXyfr4zg5Ff8TcDRwGFmzTWcqVz/HXwU8FhEjctOOEXFkmfM9D9wLfKCS8Pos/+9U9uaI2An4UC6mkr719PsKzmNtyMnChhxJb5J0hqTxaXkCWfPJPWmTucBnJI1PbexFw1yfBHYdZBjnAV+QtD2wI9lIrKeB15B9SQ90/PuA5yT9i6RXpyuTvQYY+vsF4KOSZkp6A0D63ScWxLgjWdPReknjgM+X2eaUVE+jgC8BNxYc09qUk4UNRc+RdebeK+l5siSxhKx5CLL2/zvJOpAXAj8oON6/A8ekexhmVRjDbWRNRB8HriFrwllDNrLonj7bXglMTk1OP4yIl8g64KeQjYR6CriC7KrkFSLiV8C7gLcDv0vNVv9BNpz24gFiPBvYh2yE1m2Ur4frgJ+QdYwvJxtFZfYKivDLj2zrJqmT7Et5mz5t8G1N0krgYxHx02bHYq3PVxZmZlbIycLMzAq5GcrMzAr5ysLMzApttQ8bGz16dHR2djY7DDOzIWPBggVPRURHuXVbbbLo7Oyku7u72WGYmQ0Zkvp92oGboczMrJCThZmZFXKyMDOzQk4WZmZWyMnCzMwKOVmYmVkhJwszMyvkZGFmZoWcLMzMrNBWewe3DQ2dM29r2rlXnndU085tNtT4ysLMzAo5WZiZWSEnCzMzK+RkYWZmhZwszMysUN2ShaQ5ktZJWpIru1HSojStlLQolXdKeiG37rLcPvtKelBSj6RZklSvmM3MrLx6Dp29CrgEuKZUEBHHleYlXQSsz22/PCKmlDnOpcDHgXuB24GpwB21D9fMzPpTtyuLiLgLeKbcunR1cCxw/UDHkDQW2Cki7omIIEs876txqGZmVqBZfRYHA09GxKO5somSfivpl5IOTmXjgNW5bVansrIkzZDULam7t7e39lGbmbWpZiWL6Wx+VbEWeGNEvAU4HbhO0k6DPWhEzI6Irojo6ugo+85xMzOrQsMf9yFpOPABYN9SWURsBDam+QWSlgO7A2uA8bndx6cyMzNroGZcWRwGPBIRf21ektQhaVia3xWYBKyIiLXABkkHpn6O44EfNSFmM7O2Vs+hs9cDvwH2kLRa0klp1TRe2bH9dmBxGkp7E/DJiCh1jp8MXAH0AMvxSCgzs4arWzNUREzvp/zEMmU3Azf3s303sFdNgzMzs0HxHdxmZlbIycLMzAo5WZiZWSG/Kc+A5r6xzsxan68szMyskJOFmZkVcrIwM7NCThZmZlbIycLMzAo5WZiZWSEnCzMzK+RkYWZmhZwszMyskJOFmZkVcrIwM7NCThZmZlbIycLMzAo5WZiZWSEnCzMzK1S3ZCFpjqR1kpbkys6StEbSojQdmVt3pqQeScskHZ4rn5rKeiTNrFe8ZmbWv3peWVwFTC1T/o2ImJKm2wEkTQamAXumfb4taZikYcC3gCOAycD0tK2ZmTVQ3d6UFxF3SeqscPOjgRsiYiPwmKQeYP+0riciVgBIuiFt+1Ct4zUzs/41o8/iVEmLUzPVyFQ2DliV22Z1KuuvvCxJMyR1S+ru7e2tddxmZm2r0cniUmA3YAqwFriolgePiNkR0RURXR0dHbU8tJlZW6tbM1Q5EfFkaV7S5cCtaXENMCG36fhUxgDlZmbWIA29spA0Nrf4fqA0UmoeME3SdpImApOA+4D7gUmSJkralqwTfF4jYzYzszpeWUi6HjgEGC1pNfBV4BBJU4AAVgKfAIiIpZLmknVcbwJOiYiX0nFOBe4EhgFzImJpvWI2M7Py6jkaanqZ4isH2P5c4Nwy5bcDt9cwNDMzGyTfwW1mZoWcLMzMrJCThZmZFXKyMDOzQk4WZmZWyMnCzMwKOVmYmVkhJwszMyvkZGFmZoWcLMzMrJCThZmZFXKyMDOzQk4WZmZWyMnCzMwKOVmYmVkhJwszMyvkZGFmZoWcLMzMrJCThZmZFapbspA0R9I6SUtyZRdKekTSYkm3SBqRyjslvSBpUZouy+2zr6QHJfVImiVJ9YrZzMzKq+eVxVXA1D5l84G9IuLvgN8BZ+bWLY+IKWn6ZK78UuDjwKQ09T2mmZnV2fB6HTgi7pLU2afsJ7nFe4BjBjqGpLHAThFxT1q+BngfcEdNg20RnTNva3YIZmZlNbPP4qNs/qU/UdJvJf1S0sGpbBywOrfN6lRWlqQZkroldff29tY+YjOzNtWUZCHpS8Am4NpUtBZ4Y0S8BTgduE7SToM9bkTMjoiuiOjq6OioXcBmZm2ubs1Q/ZF0IvAe4NCICICI2AhsTPMLJC0HdgfWAONzu49PZWZm1kCDurKQ9Kpq/uLP7T8V+ALw3oj4U668Q9KwNL8rWUf2iohYC2yQdGAaBXU88KNqz29mZtUpTBaSrpO0k6QdgCXAQ5I+X8F+1wO/AfaQtFrSScAlwI7A/D5DZN8OLJa0CLgJ+GREPJPWnQxcAfQAy9lKO7fNzFpZJc1QkyNig6QPkn1RzwQWABcOtFNETC9TfGU/294M3NzPum5grwriNDOzOqmkGWobSduQDVmdFxEvAlHXqMzMrKVUkiy+A6wEdgDukrQLsKGeQZmZWWspbIaKiFnArFzR45LeWb+QzMys1VTSwT1G0pWS7kjLk4ET6h6ZmZm1jEqaoa4C7gR2Tsu/A06rUzxmZtaCKkkWoyNiLvAXgIjYBLxU16jMzKylVJIsnpf0etIIKEkHAuvrGpWZmbWUSu6zOB2YB+wm6W6gg4KnxZqZ2dalktFQCyW9A9gDELAs3WthZmZtopLRUP8IvDoilpLdmHejpH3qHZiZmbWOSvosvhIRz0k6CDiU7JEdl9Y3LDMzayWVJIvSyKejgMsj4jZg2/qFZGZmraaSZLFG0neA44DbJW1X4X5mZraVqORL/1iym/IOj4hngVFA4SPKzcxs61HJ0NnRQDeApDemskfqFpGZmbWcSpLFbWQ35AnYHpgILAP2rGNcZmbWQiq5z+LN+eU0bPbkukVkZmYtZ9Ad1RGxEDigDrGYmVmLKryykHR6bvFVwD7A7+sWkZmZtZxKrix2zE3bkfVhHF3JwSXNkbRO0pJc2ShJ8yU9mn6OTOWSNEtSj6TF+bvEJZ2Qtn9Ukt+lYWbWYJX0WZwNIOm1afmPgzj+VcAlwDW5spnAzyLiPEkz0/K/AEcAk9J0ANld4gdIGgV8Fegi62hfIGleRPxhEHGYmdkWqOTZUHtJ+i2wFFgqaYGkvSo5eETcBTzTp/ho4Oo0fzXZ86ZK5ddE5h5ghKSxwOHA/Ih4JiWI+cDUSs5vZma1UUkz1Gzg9IjYJSJ2Ac5IZdUaExFr0/wTwJg0Pw5YldtudSrrr9zMzBqkkmSxQ0T8vLQQEb8AdqjFySMiSC9VqgVJMyR1S+ru7e2t1WHNzNpeJclihaSvSOpM05eBFVtwzidT8xLp57pUvgaYkNtufCrrr/wVImJ2RHRFRFdHR8cWhGhmZnmVJIuPkr0d7wdp6khl1ZoHlEY0nQD8KFd+fBoVdSCwPjVX3Qm8W9LINHLq3anMzMwapJLRUH8APlPNwSVdDxwCjJa0mmxU03nAXEknAY+TPagQ4HbgSKAH+BPwkXT+ZyT9K3B/2u6ciOjbaW5mZnVUyU15uwP/DHTmt4+IdxXtGxHT+1l1aJltAziln+PMAeYUnc/MzOqjkgcJfh+4DLiCl1+EZGZmbaSSZLEpIvwaVTOzNtZvskh3TgP8WNLJwC3AxtJ69xuYmbWPga4sFvDyeyxg87fjBbBrvYIyM7PW0m+yiIiJjQzEzMxa16DfZ2FmZu3HycLMzAr1mywkvS393K5x4ZiZWSsaqIN7FrAv8Buyt+OZWQ10zrytKedded5RTTmvbR0GShYvSpoNjJM0q+/KiKjqESBmZjb0DJQs3gMcRvbyoQWNCcfMzFrRQENnnwJukPRwRDzQwJjMzKzFVDIa6mlJt0hal6abJY2ve2RmZtYyKkkW3yV718TOafpxKjMzszZRSbJ4Q0R8NyI2pekqshcgmZlZm6gkWTwl6UOShqXpQ8DT9Q7MzMxaR6WvVT0WeAJYCxxDeoudmZm1h0peq/o48N4GxGJmZi3Kz4YyM7NCThZmZlao4clC0h6SFuWmDZJOk3SWpDW58iNz+5wpqUfSMkmHNzpmM7N2V9hnIel1wFnAwanol8A5EbG+mhNGxDJgSjr2MGAN2StbPwJ8IyK+1uf8k4FpwJ5k93n8VNLuEfFSNec3M7PBK0wWwBxgCdmIKIAPk92U94EanP9QYHlEPC6pv22OBm6IiI3AY5J6gP3JnoZrVrVmPf3VbCiqpBlqt4j4akSsSNPZ1O7929OA63PLp0paLGmOpJGpbBywKrfN6lT2CpJmSOqW1N3b21ujEM3MrJJk8YKkg0oL6aVIL2zpiSVtSzYk9/up6FJgN7ImqrXARYM9ZkTMjoiuiOjq6PBN5mZmtVJJM9QngWtS34WAZ4ATa3DuI4CFEfEkQOkngKTLgVvT4hpgQm6/8anMzMwapJKb8h4A9pa0U1reUKNzTyfXBCVpbESsTYvvJ+sngewhhtdJ+jpZB/ck4L4axWBmZhWoZDTUdsD/BDqB4aWO6Ig4p9qTStoB+AfgE7niCyRNAQJYWVoXEUslzQUeAjYBp3gklJlZY1XSDPUjYD3Z2/I21uKkEfE88Po+ZR8eYPtzgXNrcW4zMxu8SpLF+IiYWvdIzMysZVUyGurXkt5c90jMzKxlVXJlcRBwoqTHyJqhBERE/F1dIzMzs5ZRSbI4ou5RmJlZS6v0fRZmZtbG/IhyMzMr5GRhZmaFnCzMzKyQk4WZmRVysjAzs0JOFmZmVsjJwszMCjlZmJlZIScLMzMr5GRhZmaFnCzMzKyQk4WZmRVysjAzs0JOFmZmVqhpyULSSkkPSlokqTuVjZI0X9Kj6efIVC5JsyT1SFosaZ9mxW1m1o6afWXxzoiYEhFdaXkm8LOImAT8LC1D9gKmSWmaAVza8EjNzNpYs5NFX0cDV6f5q4H35cqvicw9wAhJY5sQn5lZW2pmsgjgJ5IWSJqRysZExNo0/wQwJs2PA1bl9l2dyjYjaYakbkndvb299YrbzKztVPIO7no5KCLWSHoDMF/SI/mVERGSYjAHjIjZwGyArq6uQe1rZmb9a9qVRUSsST/XAbcA+wNPlpqX0s91afM1wITc7uNTmZmZNUBTkoWkHSTtWJoH3g0sAeYBJ6TNTgB+lObnAcenUVEHAutzzVVmZlZnzWqGGgPcIqkUw3UR8R+S7gfmSjoJeBw4Nm1/O3Ak0AP8CfhI40M2M2tfTUkWEbEC2LtM+dPAoWXKAzilAaGZmVkZrTZ01szMWpCThZmZFXKyMDOzQk4WZmZWyMnCzMwKOVmYmVkhJwszMyvkZGFmZoWcLMzMrJCThZmZFXKyMDOzQk4WZmZWyMnCzMwKNfNNeWbWQJ0zb2vauVeed1TTzm214SsLMzMr5GRhZmaFnCzMzKyQk4WZmRVysjAzs0INTxaSJkj6uaSHJC2V9NlUfpakNZIWpenI3D5nSuqRtEzS4Y2O2cys3TVj6Owm4IyIWChpR2CBpPlp3Tci4mv5jSVNBqYBewI7Az+VtHtEvNTQqM3M2ljDrywiYm1ELEzzzwEPA+MG2OVo4IaI2BgRjwE9wP71j9TMzEqa2mchqRN4C3BvKjpV0mJJcySNTGXjgFW53VYzcHIxM7Maa1qykPRa4GbgtIjYAFwK7AZMAdYCF1VxzBmSuiV19/b21jJcM7O21pTHfUjahixRXBsRPwCIiCdz6y8Hbk2La4AJud3Hp7JXiIjZwGyArq6uqDa+Zj4WwcysFTVjNJSAK4GHI+LrufKxuc3eDyxJ8/OAaZK2kzQRmATc16h4zcysOVcWbwM+DDwoaVEq+yIwXdIUIICVwCcAImKppLnAQ2QjqU7xSCgzs8ZqeLKIiF8BKrPq9gH2ORc4t25BmZnZgHwHt5mZFXKyMDOzQk4WZmZWyMnCzMwKOVmYmVkhJwszMyvkZGFmZoWcLMzMrJCThZmZFXKyMDOzQk156qyZtZdmPcl55XlHNeW8WyNfWZiZWSEnCzMzK+RkYWZmhZwszMyskJOFmZkVcrIwM7NCThZmZlbIycLMzAo5WZiZWaEhkywkTZW0TFKPpJnNjsfMrJ0MiWQhaRjwLeAIYDIwXdLk5kZlZtY+hsqzofYHeiJiBYCkG4CjgYeaGpWZtbRmPZOqmer1PKyhkizGAatyy6uBA/puJGkGMCMt/lHSsgbEVonRwFPNDqIfjq06jq06jq16FcWn87foHLv0t2KoJIuKRMRsYHaz4+hLUndEdDU7jnIcW3UcW3UcW/WaHd+Q6LMA1gATcsvjU5mZmTXAUEkW9wOTJE2UtC0wDZjX5JjMzNrGkGiGiohNkk4F7gSGAXMiYmmTwxqMlmsay3Fs1XFs1XFs1WtqfIqIZp7fzMyGgKHSDGVmZk3kZGFmZoWcLLaApGGSfivp1rQ8UdK96ZEkN6bOeCRtl5Z70vrO3DHOTOXLJB1eo7hGSLpJ0iOSHpb0VkmjJM2X9Gj6OTJtK0mzUgyLJe2TO84JaftHJZ1Qo9g+J2mppCWSrpe0fbPqTdIcSeskLcmV1ayeJO0r6cG0zyxJqkF8F6Z/18WSbpE0oqhO+ntUTn/1Xm1suXVnSApJo9NyQ+uuv9gkfTrV3VJJF+TKm1pvkqZIukfSIkndkvZvRr0VighPVU7A6cB1wK1peS4wLc1fBnwqzZ8MXJbmpwE3pvnJwAPAdsBEYDkwrAZxXQ18LM1vC4wALgBmprKZwPlp/kjgDkDAgcC9qXwUsCL9HJnmR25hXOOAx4BX5+rrxGbVG/B2YB9gSa6sZvUE3Je2Vdr3iBrE925geJo/Pxdf2TpJ03Jg1/RZeACYPNDntdrYUvkEsoEojwOjm1F3/dTbO4GfAtul5Te0Sr0BPyn9fqmuftGsz9yAsdfqQO02kd3r8TPgXcCt6R/nqdx/5LcCd6b5O4G3pvnhaTsBZwJn5o751+22IK7XkX0hq0/5MmBsmh8LLEvz3wGm990OmA58J1e+2XZVxla6E39UqodbgcObWW9AZ5//uDWpp7TukVz5ZttVG1+fde8Hrk3zZeskX5/57Qb6vG5JbMBNwN7ASl5OFg2vuzL/rnOBw8ps1/R6S+c8Lve7XtfMz1x/k5uhqvdN4AvAX9Ly64FnI2JTWl5N9uUIuceVpPXr0/blHmMyji0zEegFvqusiewKSTsAYyJibdrmCWBM39j6xFDz2CJiDfA14P8Ba8nqYQGtUW8ltaqncWm+HjGWfJTsr8dq4hvo81oVSUcDayLigT6rWqHudgcOTs1Hv5S0X5Wx1bzegNOACyWtIvv/cWaVsdX1M+dkUQVJ7wHWRcSCZsdSxnCyy9xLI+ItwPNkzSl/FdmfHQ0fM53a/48mS2g7AzsAUxsdR6WaVU+VkPQlYBNwbbNjAZD0GuCLwP9qdiz9GE52RXsg8Hlgbk3b87fMp4DPRcQE4HPAlU2Opywni+q8DXivpJXADWRNUf8OjJBUutEx/0iSvz6uJK1/HfA09XmMyWpgdUTcm5ZvIkseT0oam2IYC6zrG1ufGOoR22HAYxHRGxEvAj8gq8tWqLeSWtXTmjRf8xglnQi8B/hgSmjVxPc0/dd7NXYj+yPggfT/YjywUNLfVBFbPepuNfCDyNxH1iIwuorYal1vACeQ/V8A+D7ZU7apIra6feYA91ls6QQcwssd3N9n846vk9P8KWzeUTs3ze/J5p1rK6hNB/d/AXuk+bOAC9OU77i9IM0fxeadaPel8lFkfR8j0/QYMGoL4zoAWAq8Jp3vauDTzaw3Xtl+XLN64pWdjUfWIL6pZI/m7+izXdk6IfuLekUqK3XU7jnQ57Xa2PqsW8nLfRYNr7sy9fZJ4Jw0vztZM45aod6Ah4FD0vyhwIJmfub6jbtWB2rXic2Txa7pH6snfaBKIy+2T8s9af2uuf2/RDbqYhk1GrkATAG6gcXAD9MH6vVkHfKPko0KKX24RPZiqeXAg0BX7jgfTTH3AB+pUWxnA48AS4D/m/6TNqXegOvJ+k5eJPvL86Ra1hPQlX7P5cAl9Bl0UGV8PWRfdIvSdFlRnZCNqvldWvelXHnZeq82tj7rV/Jysmho3fVTb9sC30vHXAi8q1XqDTiIrO/uAeBeYN9mfeYGmvy4DzMzK+Q+CzMzK+RkYWZmhZwszMyskJOFmZkVcrIwM7NCThZm/ZB0jqTDmh3HlpB0cHrK6iJlTx8+stkx2dDkobNmZUgaFhEvtUAcw+Pl5xBVs/9lwK8i4nvpzu+uiDi1ZgFa2/CVhbUVSZ3pnQbXKnvXx03puUZIWinpfEkLgX+UdJWkY9K6/ST9WtIDku6TtKOy95lcKOn+9L6BTwzyfPumh9otkHRn7jEjv5D0TUndwGf7HO8d6SphUXpQ5I7pvQeXpHcv/FTS7ZKOkfQx4FjgXyVdD5wDHJf2Pa6e9WxbHycLa0d7AN+OiL8FNpC9N6Pk6YjYJyJuKBWkl9vcCHw2IvYme8bVC2R3366PiP2A/YCPS5pYyfkkbQNcDBwTEfsCc4Bzc/tsGxFdEXFRn2P9M3BKREwBDk5xvD+dYzJwPPD3ABFxBTAP+HxETCd7yN+NETElIm4cRH2ZOVlYW1oVEXen+e+RPW6hpNyX6B7A2oi4HyAiNqSmoXcDx0taRPaYhtcDkyo83x7AXsD8tP+X2fwhcP19md8NfF3SZ4ARKY63A9dHxEsR8XvgP/v9zc2qNLx4E7OtTt+Ouvzy84M4joBPR8SdVZxPwNKIeGs/+5SNIyLOk3Qb2XOL7laNXsVrVsRXFtaO3iip9CX9T8CvCrZfBowtvTAn9RMMJ3vD2adSkxKSdk8vmqrkfMuAjlK5pG0k7VkUuKTdIuLBiDgfuB94E3AXWV/EsNTv8c5+dn8O2LHoHGblOFlYO1oGnCLpYbIn8l460MYR8WfgOOBiSQ8A88meiHsF2ePCF0paQvZ6y3JX6684XzrmMcD56ZiLSH0NBU6TtETSYrInl94B3EL2lNyHgGuA3/Sz78+Bye7gtmp46Ky1FUmdZI+U32trPF8651XpnDc16py29fOVhZmZFfKVhZmZFfKVhZmZFXKyMDOzQk4WZmZWyMnCzMwKOVmYmVmh/waWS31PERtrzQAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "from matplotlib import pyplot as plt\n",
    "plt.hist(df8.PRICE/df8.SQFT)\n",
    "plt.xlabel('price per sqft')\n",
    "plt.ylabel('no of houses')\n",
    "plt.title('Sqft Rate Graph')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "3aff8d59",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>AREA</th>\n",
       "      <th>SQFT</th>\n",
       "      <th>DIST_MAINROAD</th>\n",
       "      <th>NO_BED</th>\n",
       "      <th>NO_BATH</th>\n",
       "      <th>PARK</th>\n",
       "      <th>STREET</th>\n",
       "      <th>PRICE</th>\n",
       "      <th>AGE</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Karapakkam</td>\n",
       "      <td>1004</td>\n",
       "      <td>131</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1</td>\n",
       "      <td>Paved</td>\n",
       "      <td>7600000</td>\n",
       "      <td>43</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Anna Nagar</td>\n",
       "      <td>1986</td>\n",
       "      <td>26</td>\n",
       "      <td>2.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>0</td>\n",
       "      <td>Gravel</td>\n",
       "      <td>21717770</td>\n",
       "      <td>10</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Adyar</td>\n",
       "      <td>909</td>\n",
       "      <td>70</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1</td>\n",
       "      <td>Gravel</td>\n",
       "      <td>13159200</td>\n",
       "      <td>19</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Velachery</td>\n",
       "      <td>1855</td>\n",
       "      <td>14</td>\n",
       "      <td>3.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>0</td>\n",
       "      <td>Paved</td>\n",
       "      <td>9630290</td>\n",
       "      <td>21</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Karapakkam</td>\n",
       "      <td>1226</td>\n",
       "      <td>84</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1</td>\n",
       "      <td>Gravel</td>\n",
       "      <td>7406250</td>\n",
       "      <td>29</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "         AREA  SQFT  DIST_MAINROAD  NO_BED  NO_BATH  PARK  STREET     PRICE  \\\n",
       "0  Karapakkam  1004            131     1.0      1.0     1   Paved   7600000   \n",
       "1  Anna Nagar  1986             26     2.0      2.0     0  Gravel  21717770   \n",
       "2       Adyar   909             70     1.0      1.0     1  Gravel  13159200   \n",
       "3   Velachery  1855             14     3.0      2.0     0   Paved   9630290   \n",
       "4  Karapakkam  1226             84     1.0      1.0     1  Gravel   7406250   \n",
       "\n",
       "   AGE  \n",
       "0   43  \n",
       "1   10  \n",
       "2   19  \n",
       "3   21  \n",
       "4   29  "
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df9 = df8.copy()\n",
    "medianSqftPerBed2 = (df9[df9['NO_BED']==2]['SQFT']/2).median()\n",
    "medianSqftPerBed3 = (df9[df9['NO_BED']==3]['SQFT']/3).median()\n",
    "medianSqftPerBed4 = (df9[df9['NO_BED']==4]['SQFT']/4).median()\n",
    "df9.loc[(df9['NO_BATH'] < 2) & (df9['NO_BED']==2) & ((df9['SQFT']/2) > medianSqftPerBed2), 'NO_BATH'] = df9['NO_BATH']+1\n",
    "df9.loc[(df9['NO_BATH'] < 3) & (df9['NO_BED']==3) & ((df9['SQFT']/3) > medianSqftPerBed3), 'NO_BATH'] = df9['NO_BATH']+1\n",
    "df9.loc[(df9['NO_BATH'] < 4) & (df9['NO_BED']==4) & ((df9['SQFT']/4) > medianSqftPerBed4), 'NO_BATH'] = df9['NO_BATH']+1\n",
    "df9.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 58,
   "id": "a1886a5e",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>AREA</th>\n",
       "      <th>SQFT</th>\n",
       "      <th>DIST_MAINROAD</th>\n",
       "      <th>NO_BED</th>\n",
       "      <th>NO_BATH</th>\n",
       "      <th>PARK</th>\n",
       "      <th>STREET</th>\n",
       "      <th>PRICE</th>\n",
       "      <th>AGE</th>\n",
       "      <th>Gravel</th>\n",
       "      <th>Paved</th>\n",
       "      <th>Adyar</th>\n",
       "      <th>Anna Nagar</th>\n",
       "      <th>Chrompet</th>\n",
       "      <th>KK Nagar</th>\n",
       "      <th>T Nagar</th>\n",
       "      <th>Velachery</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Karapakkam</td>\n",
       "      <td>1004</td>\n",
       "      <td>131</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1</td>\n",
       "      <td>Paved</td>\n",
       "      <td>7600000</td>\n",
       "      <td>43</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Anna Nagar</td>\n",
       "      <td>1986</td>\n",
       "      <td>26</td>\n",
       "      <td>2.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>0</td>\n",
       "      <td>Gravel</td>\n",
       "      <td>21717770</td>\n",
       "      <td>10</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Adyar</td>\n",
       "      <td>909</td>\n",
       "      <td>70</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1</td>\n",
       "      <td>Gravel</td>\n",
       "      <td>13159200</td>\n",
       "      <td>19</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Velachery</td>\n",
       "      <td>1855</td>\n",
       "      <td>14</td>\n",
       "      <td>3.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>0</td>\n",
       "      <td>Paved</td>\n",
       "      <td>9630290</td>\n",
       "      <td>21</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Karapakkam</td>\n",
       "      <td>1226</td>\n",
       "      <td>84</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1</td>\n",
       "      <td>Gravel</td>\n",
       "      <td>7406250</td>\n",
       "      <td>29</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>Chrompet</td>\n",
       "      <td>1220</td>\n",
       "      <td>36</td>\n",
       "      <td>2.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0</td>\n",
       "      <td>No Access</td>\n",
       "      <td>12394750</td>\n",
       "      <td>4</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>Chrompet</td>\n",
       "      <td>1167</td>\n",
       "      <td>137</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0</td>\n",
       "      <td>No Access</td>\n",
       "      <td>8488790</td>\n",
       "      <td>27</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>Velachery</td>\n",
       "      <td>1847</td>\n",
       "      <td>176</td>\n",
       "      <td>3.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>0</td>\n",
       "      <td>Gravel</td>\n",
       "      <td>16800250</td>\n",
       "      <td>9</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>Chrompet</td>\n",
       "      <td>771</td>\n",
       "      <td>175</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0</td>\n",
       "      <td>Paved</td>\n",
       "      <td>8308970</td>\n",
       "      <td>33</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>Velachery</td>\n",
       "      <td>1635</td>\n",
       "      <td>74</td>\n",
       "      <td>2.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>0</td>\n",
       "      <td>No Access</td>\n",
       "      <td>8083650</td>\n",
       "      <td>14</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "         AREA  SQFT  DIST_MAINROAD  NO_BED  NO_BATH  PARK     STREET  \\\n",
       "0  Karapakkam  1004            131     1.0      1.0     1      Paved   \n",
       "1  Anna Nagar  1986             26     2.0      2.0     0     Gravel   \n",
       "2       Adyar   909             70     1.0      1.0     1     Gravel   \n",
       "3   Velachery  1855             14     3.0      2.0     0      Paved   \n",
       "4  Karapakkam  1226             84     1.0      1.0     1     Gravel   \n",
       "5    Chrompet  1220             36     2.0      1.0     0  No Access   \n",
       "6    Chrompet  1167            137     1.0      1.0     0  No Access   \n",
       "7   Velachery  1847            176     3.0      2.0     0     Gravel   \n",
       "8    Chrompet   771            175     1.0      1.0     0      Paved   \n",
       "9   Velachery  1635             74     2.0      2.0     0  No Access   \n",
       "\n",
       "      PRICE  AGE  Gravel  Paved  Adyar  Anna Nagar  Chrompet  KK Nagar  \\\n",
       "0   7600000   43       0      1      0           0         0         0   \n",
       "1  21717770   10       1      0      0           1         0         0   \n",
       "2  13159200   19       1      0      1           0         0         0   \n",
       "3   9630290   21       0      1      0           0         0         0   \n",
       "4   7406250   29       1      0      0           0         0         0   \n",
       "5  12394750    4       0      0      0           0         1         0   \n",
       "6   8488790   27       0      0      0           0         1         0   \n",
       "7  16800250    9       1      0      0           0         0         0   \n",
       "8   8308970   33       0      1      0           0         1         0   \n",
       "9   8083650   14       0      0      0           0         0         0   \n",
       "\n",
       "   T Nagar  Velachery  \n",
       "0        0          0  \n",
       "1        0          0  \n",
       "2        0          0  \n",
       "3        0          1  \n",
       "4        0          0  \n",
       "5        0          0  \n",
       "6        0          0  \n",
       "7        0          1  \n",
       "8        0          0  \n",
       "9        0          1  "
      ]
     },
     "execution_count": 58,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "dummiesArea = pd.get_dummies(df9.AREA)\n",
    "dummiesStreet = pd.get_dummies(df9.STREET)\n",
    "df10 = pd.concat([df9, dummiesStreet.drop(['No Access'], axis='columns'), dummiesArea.drop(['Karapakkam'], axis='columns')], axis='columns')\n",
    "#df10 = pd.concat([df9, dummiesStreet, dummiesArea], axis='columns')\n",
    "df10.head(10)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 59,
   "id": "b34cfaf8",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>SQFT</th>\n",
       "      <th>DIST_MAINROAD</th>\n",
       "      <th>NO_BED</th>\n",
       "      <th>NO_BATH</th>\n",
       "      <th>PARK</th>\n",
       "      <th>PRICE</th>\n",
       "      <th>AGE</th>\n",
       "      <th>Gravel</th>\n",
       "      <th>Paved</th>\n",
       "      <th>Adyar</th>\n",
       "      <th>Anna Nagar</th>\n",
       "      <th>Chrompet</th>\n",
       "      <th>KK Nagar</th>\n",
       "      <th>T Nagar</th>\n",
       "      <th>Velachery</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1004</td>\n",
       "      <td>131</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1</td>\n",
       "      <td>7600000</td>\n",
       "      <td>43</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1986</td>\n",
       "      <td>26</td>\n",
       "      <td>2.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>0</td>\n",
       "      <td>21717770</td>\n",
       "      <td>10</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>909</td>\n",
       "      <td>70</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1</td>\n",
       "      <td>13159200</td>\n",
       "      <td>19</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1855</td>\n",
       "      <td>14</td>\n",
       "      <td>3.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>0</td>\n",
       "      <td>9630290</td>\n",
       "      <td>21</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1226</td>\n",
       "      <td>84</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1</td>\n",
       "      <td>7406250</td>\n",
       "      <td>29</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   SQFT  DIST_MAINROAD  NO_BED  NO_BATH  PARK     PRICE  AGE  Gravel  Paved  \\\n",
       "0  1004            131     1.0      1.0     1   7600000   43       0      1   \n",
       "1  1986             26     2.0      2.0     0  21717770   10       1      0   \n",
       "2   909             70     1.0      1.0     1  13159200   19       1      0   \n",
       "3  1855             14     3.0      2.0     0   9630290   21       0      1   \n",
       "4  1226             84     1.0      1.0     1   7406250   29       1      0   \n",
       "\n",
       "   Adyar  Anna Nagar  Chrompet  KK Nagar  T Nagar  Velachery  \n",
       "0      0           0         0         0        0          0  \n",
       "1      0           1         0         0        0          0  \n",
       "2      1           0         0         0        0          0  \n",
       "3      0           0         0         0        0          1  \n",
       "4      0           0         0         0        0          0  "
      ]
     },
     "execution_count": 59,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df11 = df10.drop(['AREA', 'STREET'], axis='columns')\n",
    "df11.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 60,
   "id": "ac16fca9",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>SQFT</th>\n",
       "      <th>DIST_MAINROAD</th>\n",
       "      <th>NO_BED</th>\n",
       "      <th>NO_BATH</th>\n",
       "      <th>PARK</th>\n",
       "      <th>AGE</th>\n",
       "      <th>Gravel</th>\n",
       "      <th>Paved</th>\n",
       "      <th>Adyar</th>\n",
       "      <th>Anna Nagar</th>\n",
       "      <th>Chrompet</th>\n",
       "      <th>KK Nagar</th>\n",
       "      <th>T Nagar</th>\n",
       "      <th>Velachery</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1004</td>\n",
       "      <td>131</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1</td>\n",
       "      <td>43</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1986</td>\n",
       "      <td>26</td>\n",
       "      <td>2.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>0</td>\n",
       "      <td>10</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>909</td>\n",
       "      <td>70</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1</td>\n",
       "      <td>19</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1855</td>\n",
       "      <td>14</td>\n",
       "      <td>3.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>0</td>\n",
       "      <td>21</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1226</td>\n",
       "      <td>84</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1</td>\n",
       "      <td>29</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   SQFT  DIST_MAINROAD  NO_BED  NO_BATH  PARK  AGE  Gravel  Paved  Adyar  \\\n",
       "0  1004            131     1.0      1.0     1   43       0      1      0   \n",
       "1  1986             26     2.0      2.0     0   10       1      0      0   \n",
       "2   909             70     1.0      1.0     1   19       1      0      1   \n",
       "3  1855             14     3.0      2.0     0   21       0      1      0   \n",
       "4  1226             84     1.0      1.0     1   29       1      0      0   \n",
       "\n",
       "   Anna Nagar  Chrompet  KK Nagar  T Nagar  Velachery  \n",
       "0           0         0         0        0          0  \n",
       "1           1         0         0        0          0  \n",
       "2           0         0         0        0          0  \n",
       "3           0         0         0        0          1  \n",
       "4           0         0         0        0          0  "
      ]
     },
     "execution_count": 60,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "X = df11.drop('PRICE', axis='columns')\n",
    "X.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 61,
   "id": "ef20919b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "0     7600000\n",
       "1    21717770\n",
       "2    13159200\n",
       "3     9630290\n",
       "4     7406250\n",
       "Name: PRICE, dtype: int64"
      ]
     },
     "execution_count": 61,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "y = df11.PRICE\n",
    "y.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 135,
   "id": "f013430b",
   "metadata": {},
   "outputs": [],
   "source": [
    "#from sklearn.preprocessing import StandardScaler\n",
    "#scaler = StandardScaler()\n",
    "#X_std = scaler.fit_transform(X)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 136,
   "id": "b462d073",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.model_selection import train_test_split\n",
    "X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=10)\n",
    "#X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=10)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 137,
   "id": "adcc444f",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.model_selection import GridSearchCV\n",
    "from sklearn.model_selection import ShuffleSplit\n",
    "from sklearn.linear_model import LinearRegression\n",
    "from sklearn.linear_model import Lasso\n",
    "from sklearn.tree import DecisionTreeRegressor"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 138,
   "id": "2c9fcb04",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>model</th>\n",
       "      <th>best_score</th>\n",
       "      <th>best_params</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>linear_regression</td>\n",
       "      <td>0.615268</td>\n",
       "      <td>{}</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>decision_tree</td>\n",
       "      <td>0.217747</td>\n",
       "      <td>{'criterion': 'friedman_mse', 'splitter': 'ran...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>lasso</td>\n",
       "      <td>0.615268</td>\n",
       "      <td>{'alpha': 1, 'selection': 'cyclic'}</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "               model  best_score  \\\n",
       "0  linear_regression    0.615268   \n",
       "1      decision_tree    0.217747   \n",
       "2              lasso    0.615268   \n",
       "\n",
       "                                         best_params  \n",
       "0                                                 {}  \n",
       "1  {'criterion': 'friedman_mse', 'splitter': 'ran...  \n",
       "2                {'alpha': 1, 'selection': 'cyclic'}  "
      ]
     },
     "execution_count": 138,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def best_model(X, y):\n",
    "    algos = {\n",
    "        'linear_regression' : {\n",
    "            'model' : LinearRegression(),\n",
    "            'params' : {\n",
    "            }\n",
    "        },\n",
    "        'decision_tree' : {\n",
    "            'model' : DecisionTreeRegressor(),\n",
    "            'params' : {\n",
    "                'criterion' : ['squared_error', 'friedman_mse'],\n",
    "                'splitter' : ['best', 'random']\n",
    "            }\n",
    "        },\n",
    "        'lasso' : {\n",
    "            'model' : Lasso(),\n",
    "            'params' : {\n",
    "                'alpha' : [1,2],\n",
    "                'selection' : ['random','cyclic']\n",
    "            }\n",
    "        }\n",
    "    }\n",
    "    scores = []\n",
    "    cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)\n",
    "    for algo_name, config in algos.items():\n",
    "        gs = GridSearchCV(config['model'], config['params'], cv=cv, return_train_score=False)\n",
    "        gs.fit(X,y)\n",
    "        scores.append({\n",
    "            'model' : algo_name,\n",
    "            'best_score' : gs.best_score_,\n",
    "            'best_params' : gs.best_params_\n",
    "        })\n",
    "    return pd.DataFrame(scores, columns=['model', 'best_score', 'best_params'])\n",
    "\n",
    "best_model(X,y)\n",
    "#best_model(X_std,y)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 153,
   "id": "00dae239",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "LinearRegression()"
      ]
     },
     "execution_count": 153,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "lr = LinearRegression()\n",
    "lr.fit(X_train, y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 154,
   "id": "dc204498",
   "metadata": {},
   "outputs": [],
   "source": [
    "def predict_price(area, sqft, dist_mainroad, bed, bath, park, age, approach):\n",
    "    loc_index = -1\n",
    "    street_index = -1\n",
    "    if len(np.where(X.columns==area)[0] > 0):\n",
    "       loc_index = np.where(X.columns==area)[0][0]\n",
    "    if len(np.where(X.columns==approach)[0] > 0):\n",
    "        street_index = np.where(X.columns==approach)[0][0]\n",
    "    x = np.zeros(len(X.columns))\n",
    "    x[0] = sqft\n",
    "    x[1] = dist_mainroad\n",
    "    x[2] = bed\n",
    "    x[3] = bath\n",
    "    x[4] = park\n",
    "    x[5] = age\n",
    "    if street_index >= 0:\n",
    "        x[street_index]=1\n",
    "    if loc_index >= 0:\n",
    "        x[loc_index]=1\n",
    "    #x_std = scaler.fit_transform([x])\n",
    "    return lr.predict([x])[0]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 155,
   "id": "acd81585",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/usr/local/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "15352681.81894021"
      ]
     },
     "execution_count": 155,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "predict_price('Chrompet', 2000, 20, 3, 3, 1, 10, 'Paved')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 156,
   "id": "2b639129",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pickle\n",
    "with open('predictor.pickle', 'wb') as f:\n",
    "    pickle.dump(lr, f)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 157,
   "id": "e79abf46",
   "metadata": {},
   "outputs": [],
   "source": [
    "import json\n",
    "columns = {\n",
    "    'data_columns' : [col.lower() for col in X.columns]\n",
    "}\n",
    "with open('columns.json', 'w') as f:\n",
    "    f.write(json.dumps(columns))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b7261897",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
